apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: loki-datasource
spec:
  name: loki.yaml
  datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-stack.monitoring.svc.cluster.local:3100
      version: 1
      editable: false
