apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-datasource
spec:
  name: prometheus.yaml
  datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://thanos-query-frontend.monitoring.svc.cluster.local:9090
      version: 1
      isDefault: true
      editable: false
