apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: grafana-operator
    app.kubernetes.io/name: grafana
  name: grafana
spec:
  endpoints:
  - port: grafana
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - grafana
  selector:
    matchLabels:
      app.kubernetes.io/instance: grafana-operator
      app.kubernetes.io/name: grafana-operator
